---
apiVersion: v1
kind: Namespace
metadata:
  name: distributed-llm
  labels:
    name: distributed-llm

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: distributed-llm-agent
  namespace: distributed-llm

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: distributed-llm-agent
rules:
- apiGroups: [""]
  resources: ["nodes", "pods", "services", "endpoints"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["daemonsets"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: distributed-llm-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: distributed-llm-agent
subjects:
- kind: ServiceAccount
  name: distributed-llm-agent
  namespace: distributed-llm

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: distributed-llm-models
  namespace: distributed-llm
  labels:
    app: distributed-llm
    component: storage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: nfs-client  # Use NFS for ReadWriteMany support