---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: distributed-llm-agent
  labels:
    app: distributed-llm
    component: agent

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: distributed-llm-agent
rules:
- apiGroups: [""]
  resources: ["nodes", "pods", "services", "endpoints"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["daemonsets", "deployments"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: distributed-llm-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: distributed-llm-agent
subjects:
- kind: ServiceAccount
  name: distributed-llm-agent
  namespace: default
