---
apiVersion: v1
kind: Service
metadata:
  name: distributed-llm-agent
  labels:
    app: distributed-llm
    component: agent
spec:
  type: ClusterIP
  clusterIP: None  # Headless service for peer discovery
  ports:
  - name: grpc
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: gossip
    port: 7946
    targetPort: 7946
    protocol: TCP
  - name: gossip-udp
    port: 7946
    targetPort: 7946
    protocol: UDP
  selector:
    app: distributed-llm-agent

---
apiVersion: v1
kind: Service
metadata:
  name: distributed-llm-api
  labels:
    app: distributed-llm
    component: api
spec:
  type: LoadBalancer
  ports:
  - name: grpc
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: distributed-llm-agent

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: distributed-llm-config
data:
  config.yaml: |
    network:
      gossip_port: 7946
      grpc_port: 8080
      discovery_service: "distributed-llm-agent.default.svc.cluster.local"
    
    storage:
      models_path: "/models"
      shared_storage: true
    
    llm:
      max_layers_per_node: 20
      context_size: 4096
      
    logging:
      level: "info"
      format: "json"