//go:generate sh -c "git rev-parse --short HEAD > version.txt"

// This file is generated by go generate. Do not edit manually.
package main

import _ "embed"

// Version holds the current git commit hash
//
//go:embed version.txt
var Version string
